spring.application.name=powerr
spring.datasource.url=jdbc:postgresql://localhost:5432/powerr
spring.datasource.username=postgres
spring.datasource.password=zxca
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.error.include-binding-errors=always
server.error.include-message=always

spring.jpa.ddl


#logging.level.org.springframework.security=TRACE