server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: zxca
    url: jdbc:postgresql://localhost:5432/powerr
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true